name: GitHub Actions Demo

on:
  schedule:
    - cron: '0 2 * * *'  # Esto configura el workflow para ejecutarse diariamente a las 2:00 AM UTC

jobs:
  daily-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Make changes
      run: |
        # Aquí puedes hacer los cambios que necesitas en tu repositorio
        # Por ejemplo, crear o modificar un archivo
        echo "This is an automated commit" > automated_file.txt
        git add automated_file.txt
        git commit -m "Automated commit"

    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
